from zipfile import ZipFile
import shutil, os
import sys

import tkinter as tk
root = tk.Tk()
root.title("===> Qmail <===")

e = tk.Entry(root, width=40, fg="blue", bg="yellow", borderwidth=13)
#e.pack()
e.grid(row=0,column=0)
e.insert(0, "Name of person who gets the message")

e1 = tk.Entry(root, width=20, fg="blue", bg="yellow", borderwidth=13)
#e1.pack()
e1.grid(row=0,column=1)
e1.insert(0, "Enter the file name: ")

e2 = tk.Entry(root, width=40, fg="blue", bg="yellow", borderwidth=13)
#e2.pack()
e2.grid(row=2,column=0)
e2.insert(0, "Name of person who sends the message")

def EncryptAES256():
        one = e.get()
        two = e1.get()
        three = e2.get()
        #clear screen
        print("\033[H\033[J")

        print("Menu 1 has been selected")
        print("*** Encrypting Message")
        # copy two from message to current directory
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("MESSAGE")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ( two )
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = (two)
        destination = (os.path.join(currentDirectory, filenamepk))
        newpath = shutil.copy(source, destination)
        print (newpath)
        os.remove(source)
        # delete keys
        os.remove("pk.txt")
        os.remove("sk.txt")
        # copy pk.txt from frodo
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("keysfrodo")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ("pk" + one + ".txt")
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = ("pk" + ".txt")
        destination = (os.path.join(currentDirectory, filenamepk))
        newpath = shutil.copy(source, destination)
        # copy sk.txt from frodo
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("keysfrodo")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ("pk" + one + ".txt")
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = ("sk" + ".txt")
        destination = (os.path.join(currentDirectory, filenamepk))
        newpath = shutil.copy(source, destination)
        #pause = (input("hit enter to continue: "))
        temp = os.system('python enc1.py')
        symfile = ("gpg --yes --batch --passphrase=" + str(temp) + " --symmetric --cipher-algo AES256 " + two )
        #print (symfile)
        os.system(symfile)
        #pause = (input("hit enter to continue: "))
        # delete keys
        os.remove("pk.txt")
        os.remove("sk.txt")
        # copy pk.txt from falcon
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("keysfalcon")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ("pk" + three + ".txt")
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = ("pk" + ".txt")
        destination = (os.path.join(currentDirectory, filenamepk))
        shutil.copy(source, destination)
        # copy sk.txt from falcon
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("keysfalcon")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ("sk" + three + ".txt")
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = ("sk" + ".txt")
        destination = (os.path.join(currentDirectory, filenamepk))
        shutil.copy(source, destination)
        # python SignFile with file 
        signfile = ("python SignFile.py " + two + " " + two + ".sig" )
        os.system( signfile )
        #pause = (input("hit enter to continue: "))
        # copy ct to msg directory 
        #currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = ("ct" + ".txt")
        #source = (os.path.join(currentDirectory, filenamepk))
        #currentDirectory = os.path.abspath(os.getcwd())
        #subdir = ("MESSAGE")
        #currentDirectory = (os.path.join(currentDirectory, subdir))
        #filenamepk = ("ct" + ".txt")
        #destination = (os.path.join(currentDirectory, filenamepk)) 
        #shutil.copy(source, destination)
        # copy gpg to msg directory
        #currentDirectory = os.path.abspath(os.getcwd())
        filenamepk1 = (two + ".gpg")
        #source = (os.path.join(currentDirectory, filenamepk1))
        #currentDirectory = os.path.abspath(os.getcwd())
        #subdir = ("MESSAGE")
        #currentDirectory = (os.path.join(currentDirectory, subdir))
        #filenamepk1 = (two + ".gpg")
        #destination = (os.path.join(currentDirectory, filenamepk1)) 
        #shutil.copy(source, destination)        
        # copy sig to msg directory
        #currentDirectory = os.path.abspath(os.getcwd())
        filenamepk2 = (two + ".sig")
        #source = (os.path.join(currentDirectory, filenamepk2))
        #currentDirectory = os.path.abspath(os.getcwd())
        #subdir = ("MESSAGE")
        #currentDirectory = (os.path.join(currentDirectory, subdir))
        #filenamepk2 = (two + ".sig")
        #destination = (os.path.join(currentDirectory, filenamepk2)) 
        #shutil.copy(source, destination) 
        #create zipfile
        # create a ZipFile object
        zipObj = ZipFile(two + ".zip", "w")
        # Add multiple files to the zip
        zipObj.write("ct" + ".txt")
        zipObj.write(two + ".gpg")
        zipObj.write(two + ".sig")
        # close the Zip File
        zipObj.close()  
        # copy zipObj to msg directory 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = (two + ".zip")
        source = (os.path.join(currentDirectory, filenamepk))
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("MESSAGE")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = (two + ".zip")
        destination = (os.path.join(currentDirectory, filenamepk)) 
        shutil.copy(source, destination)     
        #delete ct
        os.remove("ct.txt")
        #delete two 
        filename = (two)
        os.remove(filename)
        #delete two + .gpg
        filename = (two + ".gpg")
        os.remove(filename)
        #delete two + .sig
        filename = (two + ".sig")
        os.remove(filename)
        #delete two + .zip
        filename = (two + ".zip")
        os.remove(filename)
        #clear screen
        #print("\033[H\033[J")
    

def EncryptCAMELLIA256():
        one = e.get()
        two = e1.get()
        three = e2.get()
        #clear screen
        print("\033[H\033[J")

        print("Menu 7 has been selected")
        print("*** Encrypting Message")
        # copy two from message to current directory
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("MESSAGE")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ( two )
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = (two)
        destination = (os.path.join(currentDirectory, filenamepk))
        newpath = shutil.copy(source, destination)
        print (newpath)
        os.remove(source)
        # delete keys
        os.remove("pk.txt")
        os.remove("sk.txt")
        # copy pk.txt from frodo
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("keysfrodo")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ("pk" + one + ".txt")
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = ("pk" + ".txt")
        destination = (os.path.join(currentDirectory, filenamepk))
        newpath = shutil.copy(source, destination)
        # copy sk.txt from frodo
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("keysfrodo")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ("pk" + one + ".txt")
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = ("sk" + ".txt")
        destination = (os.path.join(currentDirectory, filenamepk))
        newpath = shutil.copy(source, destination)
        #pause = (input("hit enter to continue: "))
        temp = os.system('python enc1.py')
        symfile = ("gpg --yes --batch --passphrase=" + str(temp) + " --symmetric --cipher-algo CAMELLIA256 " + two )
        print (symfile)
        os.system(symfile)
        #pause = (input("hit enter to continue: "))
        # delete keys
        os.remove("pk.txt")
        os.remove("sk.txt")
        # copy pk.txt from falcon
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("keysfalcon")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ("pk" + three + ".txt")
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = ("pk" + ".txt")
        destination = (os.path.join(currentDirectory, filenamepk))
        shutil.copy(source, destination)
        # copy sk.txt from falcon
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("keysfalcon")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ("sk" + three + ".txt")
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = ("sk" + ".txt")
        destination = (os.path.join(currentDirectory, filenamepk))
        shutil.copy(source, destination)
        # python SignFile with file 
        signfile = ("python SignFile.py " + two + " " + two + ".sig" )
        os.system( signfile )
        #pause = (input("hit enter to continue: "))
        # copy ct to msg directory 
        #currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = ("ct" + ".txt")
        #source = (os.path.join(currentDirectory, filenamepk))
        #currentDirectory = os.path.abspath(os.getcwd())
        #subdir = ("MESSAGE")
        #currentDirectory = (os.path.join(currentDirectory, subdir))
        #filenamepk = ("ct" + ".txt")
        #destination = (os.path.join(currentDirectory, filenamepk)) 
        #shutil.copy(source, destination)
        # copy gpg to msg directory
        #currentDirectory = os.path.abspath(os.getcwd())
        filenamepk1 = (two + ".gpg")
        #source = (os.path.join(currentDirectory, filenamepk1))
        #currentDirectory = os.path.abspath(os.getcwd())
        #subdir = ("MESSAGE")
        #currentDirectory = (os.path.join(currentDirectory, subdir))
        #filenamepk1 = (two + ".gpg")
        #destination = (os.path.join(currentDirectory, filenamepk1)) 
        #shutil.copy(source, destination)        
        # copy sig to msg directory
        #currentDirectory = os.path.abspath(os.getcwd())
        filenamepk2 = (two + ".sig")
        #source = (os.path.join(currentDirectory, filenamepk2))
        #currentDirectory = os.path.abspath(os.getcwd())
        #subdir = ("MESSAGE")
        #currentDirectory = (os.path.join(currentDirectory, subdir))
        #filenamepk2 = (two + ".sig")
        #destination = (os.path.join(currentDirectory, filenamepk2)) 
        #shutil.copy(source, destination) 
        #create zipfile
        # create a ZipFile object
        zipObj = ZipFile(two + ".zip", "w")
        # Add multiple files to the zip
        zipObj.write("ct" + ".txt")
        zipObj.write(two + ".gpg")
        zipObj.write(two + ".sig")
        # close the Zip File
        zipObj.close()  
        # copy zipObj to msg directory 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = (two + ".zip")
        source = (os.path.join(currentDirectory, filenamepk))
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("MESSAGE")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = (two + ".zip")
        destination = (os.path.join(currentDirectory, filenamepk)) 
        shutil.copy(source, destination)       
        #delete ct
        os.remove("ct.txt")
        #delete two 
        filename = (two)
        os.remove(filename)
        #delete two + .gpg
        filename = (two + ".gpg")
        os.remove(filename)
        #delete two + .sig
        filename = (two + ".sig")
        os.remove(filename)
        #delete two + .zip
        filename = (two + ".zip")
        os.remove(filename)
        #clear screen
        #print("\033[H\033[J")

def Decrypt():
        one = e.get()
        two = e1.get()
        three = e2.get()
        #clear screen
        print("\033[H\033[J")

        print("Menu 2 has been selected")
        # copy two + .zip from message to current directory
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("MESSAGE")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ( two + ".zip" )
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = (two + ".zip")
        destination = (os.path.join(currentDirectory, filenamepk))
        newpath = shutil.copy(source, destination)
        print (newpath)
        os.remove(source)
        # Create a ZipFile Object and load sample.zip in it
        with ZipFile(two + ".zip", 'r') as zipObj:
        # Extract all the contents of zip file in different directory
           zipObj.extractall("MESSAGE")
        print("*** Decrypting Message")
        #delete two + .zip
        filename = (two + ".zip")
        os.remove(filename)
        # copy ct.txt from message to current directory
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("MESSAGE")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ( "ct.txt" )
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = ("ct.txt")
        destination = (os.path.join(currentDirectory, filenamepk))
        newpath = shutil.copy(source, destination)
        print (newpath)
        os.remove(source)
        # copy two.gpg from message to current directory
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("MESSAGE")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ( two + ".gpg")
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = (two + ".gpg")
        destination = (os.path.join(currentDirectory, filenamepk))
        newpath = shutil.copy(source, destination)
        print (newpath)
        os.remove(source)
        # copy two.sig from message to current directory
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("MESSAGE")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ( two + ".sig" )
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = (two + ".sig")
        destination = (os.path.join(currentDirectory, filenamepk))
        newpath = shutil.copy(source, destination)
        print (newpath)
        os.remove(source)
        # delete keys
        os.remove("pk.txt")
        os.remove("sk.txt")
        # copy pk.txt from frodo
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("keysfrodo")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ("pk" + one + ".txt")
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = ("pk" + ".txt")
        destination = (os.path.join(currentDirectory, filenamepk))
        shutil.copy(source, destination)
        # copy sk.txt from frodo
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("keysfrodo")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ("sk" + one + ".txt")
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = ("sk" + ".txt")
        destination = (os.path.join(currentDirectory, filenamepk))
        shutil.copy(source, destination)
        #pause = (input("hit enter to continue: "))
        #os.system('python dec.py')
        #symfile = ("gpg -o " + two + " -d " + two + ".gpg")
        os.system('python Dec1.py')
        temp = os.system('python Dec1.py')
        temp= str(temp)
        symfile = ("gpg  --yes --batch --passphrase=" + temp + " -o " + two + " -d " + two + ".gpg")
        print(symfile)
        #pause = (input("hit enter to continue: "))
        os.system(symfile)
        #pause = (input("hit enter to continue: "))
        # delete keys
        os.remove("pk.txt")
        os.remove("sk.txt")
        # copy pk.txt from falcon
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("keysfalcon")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ("pk" + three + ".txt")
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = ("pk" + ".txt")
        destination = (os.path.join(currentDirectory, filenamepk))
        shutil.copy(source, destination)
        # copy sk.txt from falcon
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("keysfalcon")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ("pk" + three + ".txt")
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = ("sk" + ".txt")
        destination = (os.path.join(currentDirectory, filenamepk))
        shutil.copy(source, destination)
        # python VerifyFile with file 
        signfile = ("python VerifyFile.py " + two + " " + two + ".sig" )
        os.system( signfile )
        #pause = (input("hit enter to continue: "))
        # copy ct to msg directory 
        #currentDirectory = os.path.abspath(os.getcwd())
        #filenamepk = ("ct" + ".txt")
        #source = (os.path.join(currentDirectory, filenamepk))
        #currentDirectory = os.path.abspath(os.getcwd())
        #subdir = ("MESSAGE")
        #currentDirectory = (os.path.join(currentDirectory, subdir))
        #filenamepk = ("ct" + ".txt")
        #destination = (os.path.join(currentDirectory, filenamepk)) 
        #shutil.copy(source, destination)
        # copy two to msg directory
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = (two)
        source = (os.path.join(currentDirectory, filenamepk))
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("MESSAGE")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = (two)
        destination = (os.path.join(currentDirectory, filenamepk)) 
        shutil.copy(source, destination)        
        # copy gpg to msg directory
        #currentDirectory = os.path.abspath(os.getcwd())
        #filenamepk = (two + ".gpg")
        #source = (os.path.join(currentDirectory, filenamepk))
        #currentDirectory = os.path.abspath(os.getcwd())
        #subdir = ("MESSAGE")
        #currentDirectory = (os.path.join(currentDirectory, subdir))
        #filenamepk = (two + ".gpg")
        #destination = (os.path.join(currentDirectory, filenamepk)) 
        #shutil.copy(source, destination)        
        # copy sig to msg directory
        #currentDirectory = os.path.abspath(os.getcwd())
        #filenamepk = (two + ".sig")
        #source = (os.path.join(currentDirectory, filenamepk))
        #currentDirectory = os.path.abspath(os.getcwd())
        #subdir = ("MESSAGE")
        #currentDirectory = (os.path.join(currentDirectory, subdir))
        #filenamepk = (two + ".sig")
        #destination = (os.path.join(currentDirectory, filenamepk)) 
        #shutil.copy(source, destination)  
        #delete ct
        os.remove("ct.txt")
        #delete two 
        filename = (two)
        os.remove(filename)
        #delete two + .gpg
        filename = (two + ".gpg")
        os.remove(filename)
        #delete two + .sig
        filename = (two + ".sig")
        os.remove(filename)
        #clear screen
        #print("\033[H\033[J")

def KeyGenFrodo():
        one = e.get()
        two = e1.get()
        three = e2.get()
        #clear screen
        print("\033[H\033[J")

        print("*** Generating Keys")
        print("Menu 3 has been selected")
        os.system('python keygen.py')
        # copy pk.txt to frodo
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("keysfrodo")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ("pk" + one + ".txt")
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = ("pk" + ".txt")
        destination = (os.path.join(currentDirectory, filenamepk))
        shutil.copy(destination, source)
        # copy sk.txt to frodo
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("keysfrodo")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ("sk" + one + ".txt")
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = ("sk" + ".txt")
        destination = (os.path.join(currentDirectory, filenamepk))
        shutil.copy(destination, source)
        #pause = (input("hit enter to continue: "))
        #print("\033[H\033[J")

def KeyGenFalcon():
        one = e.get()
        two = e1.get()
        three = e2.get()
        #clear screen
        print("\033[H\033[J")

        print("*** Generating Keys")
        #clear screen
        print("\033[H\033[J")
        print("Menu 4 has been selected")
        os.system('python keygen.py')
        # copy pk.txt to falcon
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("keysfalcon")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ("pk" + one + ".txt")
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = ("pk" + ".txt")
        destination = (os.path.join(currentDirectory, filenamepk))
        shutil.copy(destination, source)
        # copy sk.txt to falcon
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("keysfalcon")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ("sk" + one + ".txt")
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = ("sk" + ".txt")
        destination = (os.path.join(currentDirectory, filenamepk))
        shutil.copy(destination, source)
        #pause = (input("hit enter to continue: "))
        #print("\033[H\033[J")

def OTPEncryptAES256():
        one = e.get()
        two = e1.get()
        three = e2.get()
        #clear screen
        print("\033[H\033[J")

        print("Menu 5 has been selected")
        print("*** OTP Encrypting Message")
        # copy two from message to current directory
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("MESSAGE")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ( two )
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = (two)
        destination = (os.path.join(currentDirectory, filenamepk))
        newpath = shutil.copy(source, destination)
        print (newpath)
        os.remove(source)
        #pause = (input("hit enter to continue: "))
        symfile = ("python xorenc.py " + two + " keyotp.txt " + two + ".otp" )
        print (symfile)
        os.system(symfile)
        #pause = (input("hit enter to continue: "))
        # copy .otp from to message directory
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = (two + ".otp")
        source = (os.path.join(currentDirectory, filenamepk))
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("MESSAGE")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = (two + ".otp")
        destination = (os.path.join(currentDirectory, filenamepk)) 
        shutil.copy(source, destination)
        filenamepkotp = (two + ".otp")
        # copy keyotp.txt to msg directory
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = ("keyotp.txt")
        source = (os.path.join(currentDirectory, filenamepk))
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("MESSAGE")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ("keyotp.txt")
        destination = (os.path.join(currentDirectory, filenamepk)) 
        shutil.copy(source, destination) 
        filenamepkotpkey = ("keyotp.txt")
        #delete two 
        filename = (two)
        os.remove(filename)             
        #delete .otp
        os.remove(two + ".otp")
        #delete keyotp.txt 
        filename = ("keyotp.txt")
        os.remove(filename)
        #encrypt filenamepkotp

        two = filenamepkotp
        ### copy two from message to current directory
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("MESSAGE")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ( two )
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = (two)
        destination = (os.path.join(currentDirectory, filenamepk))
        newpath = shutil.copy(source, destination)
        print (newpath)
        os.remove(source)
        # delete keys
        os.remove("pk.txt")
        os.remove("sk.txt")
        # copy pk.txt from frodo
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("keysfrodo")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ("pk" + one + ".txt")
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = ("pk" + ".txt")
        destination = (os.path.join(currentDirectory, filenamepk))
        newpath = shutil.copy(source, destination)
        # copy sk.txt from frodo
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("keysfrodo")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ("pk" + one + ".txt")
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = ("sk" + ".txt")
        destination = (os.path.join(currentDirectory, filenamepk))
        newpath = shutil.copy(source, destination)
        #pause = (input("hit enter to continue: "))
        temp = os.system('python enc1.py')
        symfile = ("gpg --yes --batch --passphrase=" + str(temp) + " --symmetric --cipher-algo AES256 " + two )
        print (symfile)
        os.system(symfile)
        #pause = (input("hit enter to continue: "))
        # delete keys
        os.remove("pk.txt")
        os.remove("sk.txt")
        # copy pk.txt from falcon
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("keysfalcon")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ("pk" + three + ".txt")
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = ("pk" + ".txt")
        destination = (os.path.join(currentDirectory, filenamepk))
        shutil.copy(source, destination)
        # copy sk.txt from falcon
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("keysfalcon")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ("sk" + three + ".txt")
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = ("sk" + ".txt")
        destination = (os.path.join(currentDirectory, filenamepk))
        shutil.copy(source, destination)
        # python SignFile with file 
        signfile = ("python SignFile.py " + two + " " + two + ".sig" )
        os.system( signfile )
        #pause = (input("hit enter to continue: "))
        # copy ct to msg directory 
        #currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = ("ct" + ".txt")
        #source = (os.path.join(currentDirectory, filenamepk))
        #currentDirectory = os.path.abspath(os.getcwd())
        #subdir = ("MESSAGE")
        #currentDirectory = (os.path.join(currentDirectory, subdir))
        #filenamepk = ("ct" + ".txt")
        #destination = (os.path.join(currentDirectory, filenamepk)) 
        #shutil.copy(source, destination)
        # copy gpg to msg directory
        #currentDirectory = os.path.abspath(os.getcwd())
        filenamepk1 = (two + ".gpg")
        #source = (os.path.join(currentDirectory, filenamepk1))
        #currentDirectory = os.path.abspath(os.getcwd())
        #subdir = ("MESSAGE")
        #currentDirectory = (os.path.join(currentDirectory, subdir))
        #filenamepk1 = (two + ".gpg")
        #destination = (os.path.join(currentDirectory, filenamepk1)) 
        #shutil.copy(source, destination)        
        # copy sig to msg directory
        #currentDirectory = os.path.abspath(os.getcwd())
        filenamepk2 = (two + ".sig")
        #source = (os.path.join(currentDirectory, filenamepk2))
        #currentDirectory = os.path.abspath(os.getcwd())
        #subdir = ("MESSAGE")
        #currentDirectory = (os.path.join(currentDirectory, subdir))
        #filenamepk2 = (two + ".sig")
        #destination = (os.path.join(currentDirectory, filenamepk2)) 
        #shutil.copy(source, destination) 
        #create zipfile
        # create a ZipFile object
        zipObj = ZipFile(two + ".zip", "w")
        # Add multiple files to the zip
        zipObj.write("ct" + ".txt")
        zipObj.write(two + ".gpg")
        zipObj.write(two + ".sig")
        # close the Zip File
        zipObj.close()  
        # copy zipObj to msg directory 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = (two + ".zip")
        source = (os.path.join(currentDirectory, filenamepk))
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("MESSAGE")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = (two + ".zip")
        destination = (os.path.join(currentDirectory, filenamepk)) 
        shutil.copy(source, destination)     
        #delete ct
        os.remove("ct.txt")
        #delete two 
        filename = (two)
        os.remove(filename)
        #delete two + .gpg
        filename = (two + ".gpg")
        os.remove(filename)
        #delete two + .sig
        filename = (two + ".sig")
        os.remove(filename)
        #delete two + .zip
        filename = (two + ".zip")
        os.remove(filename)

        two = filenamepkotpkey
        ### copy two from message to current directory
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("MESSAGE")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ( two )
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = (two)
        destination = (os.path.join(currentDirectory, filenamepk))
        newpath = shutil.copy(source, destination)
        print (newpath)
        os.remove(source)
        # delete keys
        os.remove("pk.txt")
        os.remove("sk.txt")
        # copy pk.txt from frodo
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("keysfrodo")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ("pk" + one + ".txt")
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = ("pk" + ".txt")
        destination = (os.path.join(currentDirectory, filenamepk))
        newpath = shutil.copy(source, destination)
        # copy sk.txt from frodo
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("keysfrodo")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ("pk" + one + ".txt")
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = ("sk" + ".txt")
        destination = (os.path.join(currentDirectory, filenamepk))
        newpath = shutil.copy(source, destination)
        #pause = (input("hit enter to continue: "))
        temp = os.system('python enc1.py')
        symfile = ("gpg --yes --batch --passphrase=" + str(temp) + " --symmetric --cipher-algo AES256 " + two )
        print (symfile)
        os.system(symfile)
        #pause = (input("hit enter to continue: "))
        # delete keys
        os.remove("pk.txt")
        os.remove("sk.txt")
        # copy pk.txt from falcon
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("keysfalcon")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ("pk" + three + ".txt")
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = ("pk" + ".txt")
        destination = (os.path.join(currentDirectory, filenamepk))
        shutil.copy(source, destination)
        # copy sk.txt from falcon
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("keysfalcon")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ("sk" + three + ".txt")
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = ("sk" + ".txt")
        destination = (os.path.join(currentDirectory, filenamepk))
        shutil.copy(source, destination)
        # python SignFile with file 
        signfile = ("python SignFile.py " + two + " " + two + ".sig" )
        os.system( signfile )
        #pause = (input("hit enter to continue: "))
        # copy ct to msg directory 
        #currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = ("ct" + ".txt")
        #source = (os.path.join(currentDirectory, filenamepk))
        #currentDirectory = os.path.abspath(os.getcwd())
        #subdir = ("MESSAGE")
        #currentDirectory = (os.path.join(currentDirectory, subdir))
        #filenamepk = ("ct" + ".txt")
        #destination = (os.path.join(currentDirectory, filenamepk)) 
        #shutil.copy(source, destination)
        # copy gpg to msg directory
        #currentDirectory = os.path.abspath(os.getcwd())
        filenamepk1 = (two + ".gpg")
        #source = (os.path.join(currentDirectory, filenamepk1))
        #currentDirectory = os.path.abspath(os.getcwd())
        #subdir = ("MESSAGE")
        #currentDirectory = (os.path.join(currentDirectory, subdir))
        #filenamepk1 = (two + ".gpg")
        #destination = (os.path.join(currentDirectory, filenamepk1)) 
        #shutil.copy(source, destination)        
        # copy sig to msg directory
        #currentDirectory = os.path.abspath(os.getcwd())
        filenamepk2 = (two + ".sig")
        #source = (os.path.join(currentDirectory, filenamepk2))
        #currentDirectory = os.path.abspath(os.getcwd())
        #subdir = ("MESSAGE")
        #currentDirectory = (os.path.join(currentDirectory, subdir))
        #filenamepk2 = (two + ".sig")
        #destination = (os.path.join(currentDirectory, filenamepk2)) 
        #shutil.copy(source, destination) 
        #create zipfile
        # create a ZipFile object
        zipObj = ZipFile(two + ".zip", "w")
        # Add multiple files to the zip
        zipObj.write("ct" + ".txt")
        zipObj.write(two + ".gpg")
        zipObj.write(two + ".sig")
        # close the Zip File
        zipObj.close()  
        # copy zipObj to msg directory 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = (two + ".zip")
        source = (os.path.join(currentDirectory, filenamepk))
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("MESSAGE")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = (two + ".zip")
        destination = (os.path.join(currentDirectory, filenamepk)) 
        shutil.copy(source, destination)     
        #delete ct
        os.remove("ct.txt")
        #delete two 
        filename = (two)
        os.remove(filename)
        #delete two + .gpg
        filename = (two + ".gpg")
        os.remove(filename)
        #delete two + .sig
        filename = (two + ".sig")
        os.remove(filename)
        #delete two + .zip
        filename = (two + ".zip")
        os.remove(filename)

        #pause = (input("hit enter to continue: "))
        #clear screen
        #print("\033[H\033[J")

def OTPEncryptCAMELLIA256():
        one = e.get()
        two = e1.get()
        three = e2.get()
        #clear screen
        print("\033[H\033[J")

        print("Menu 8 has been selected")
        print("*** OTP Encrypting Message")
        # copy two from message to current directory
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("MESSAGE")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ( two )
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = (two)
        destination = (os.path.join(currentDirectory, filenamepk))
        newpath = shutil.copy(source, destination)
        print (newpath)
        os.remove(source)
        #pause = (input("hit enter to continue: "))
        symfile = ("python xorenc.py " + two + " keyotp.txt " + two + ".otp" )
        print (symfile)
        os.system(symfile)
        #pause = (input("hit enter to continue: "))
        # copy .otp from to message directory
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = (two + ".otp")
        source = (os.path.join(currentDirectory, filenamepk))
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("MESSAGE")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = (two + ".otp")
        destination = (os.path.join(currentDirectory, filenamepk)) 
        shutil.copy(source, destination)
        filenamepkotp = (two + ".otp")
        # copy keyotp.txt to msg directory
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = ("keyotp.txt")
        source = (os.path.join(currentDirectory, filenamepk))
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("MESSAGE")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ("keyotp.txt")
        destination = (os.path.join(currentDirectory, filenamepk)) 
        shutil.copy(source, destination) 
        filenamepkotpkey = ("keyotp.txt")
        #delete two 
        filename = (two)
        os.remove(filename)             
        #delete .otp
        os.remove(two + ".otp")
        #delete keyotp.txt 
        filename = ("keyotp.txt")
        os.remove(filename)
        #encrypt filenamepkotp

        two = filenamepkotp
        ### copy two from message to current directory
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("MESSAGE")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ( two )
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = (two)
        destination = (os.path.join(currentDirectory, filenamepk))
        newpath = shutil.copy(source, destination)
        print (newpath)
        os.remove(source)
        # delete keys
        os.remove("pk.txt")
        os.remove("sk.txt")
        # copy pk.txt from frodo
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("keysfrodo")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ("pk" + one + ".txt")
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = ("pk" + ".txt")
        destination = (os.path.join(currentDirectory, filenamepk))
        newpath = shutil.copy(source, destination)
        # copy sk.txt from frodo
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("keysfrodo")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ("pk" + one + ".txt")
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = ("sk" + ".txt")
        destination = (os.path.join(currentDirectory, filenamepk))
        newpath = shutil.copy(source, destination)
        #pause = (input("hit enter to continue: "))
        temp = os.system('python enc1.py')
        symfile = ("gpg --yes --batch --passphrase=" + str(temp) + " --symmetric --cipher-algo CAMELLIA256 " + two )
        print (symfile)
        os.system(symfile)
        #pause = (input("hit enter to continue: "))
        # delete keys
        os.remove("pk.txt")
        os.remove("sk.txt")
        # copy pk.txt from falcon
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("keysfalcon")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ("pk" + three + ".txt")
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = ("pk" + ".txt")
        destination = (os.path.join(currentDirectory, filenamepk))
        shutil.copy(source, destination)
        # copy sk.txt from falcon
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("keysfalcon")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ("sk" + three + ".txt")
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = ("sk" + ".txt")
        destination = (os.path.join(currentDirectory, filenamepk))
        shutil.copy(source, destination)
        # python SignFile with file 
        signfile = ("python SignFile.py " + two + " " + two + ".sig" )
        os.system( signfile )
        #pause = (input("hit enter to continue: "))
        # copy ct to msg directory 
        #currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = ("ct" + ".txt")
        #source = (os.path.join(currentDirectory, filenamepk))
        #currentDirectory = os.path.abspath(os.getcwd())
        #subdir = ("MESSAGE")
        #currentDirectory = (os.path.join(currentDirectory, subdir))
        #filenamepk = ("ct" + ".txt")
        #destination = (os.path.join(currentDirectory, filenamepk)) 
        #shutil.copy(source, destination)
        # copy gpg to msg directory
        #currentDirectory = os.path.abspath(os.getcwd())
        filenamepk1 = (two + ".gpg")
        #source = (os.path.join(currentDirectory, filenamepk1))
        #currentDirectory = os.path.abspath(os.getcwd())
        #subdir = ("MESSAGE")
        #currentDirectory = (os.path.join(currentDirectory, subdir))
        #filenamepk1 = (two + ".gpg")
        #destination = (os.path.join(currentDirectory, filenamepk1)) 
        #shutil.copy(source, destination)        
        # copy sig to msg directory
        #currentDirectory = os.path.abspath(os.getcwd())
        filenamepk2 = (two + ".sig")
        #source = (os.path.join(currentDirectory, filenamepk2))
        #currentDirectory = os.path.abspath(os.getcwd())
        #subdir = ("MESSAGE")
        #currentDirectory = (os.path.join(currentDirectory, subdir))
        #filenamepk2 = (two + ".sig")
        #destination = (os.path.join(currentDirectory, filenamepk2)) 
        #shutil.copy(source, destination) 
        #create zipfile
        # create a ZipFile object
        zipObj = ZipFile(two + ".zip", "w")
        # Add multiple files to the zip
        zipObj.write("ct" + ".txt")
        zipObj.write(two + ".gpg")
        zipObj.write(two + ".sig")
        # close the Zip File
        zipObj.close()  
        # copy zipObj to msg directory 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = (two + ".zip")
        source = (os.path.join(currentDirectory, filenamepk))
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("MESSAGE")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = (two + ".zip")
        destination = (os.path.join(currentDirectory, filenamepk)) 
        shutil.copy(source, destination)     
        #delete ct
        os.remove("ct.txt")
        #delete two 
        filename = (two)
        os.remove(filename)
        #delete two + .gpg
        filename = (two + ".gpg")
        os.remove(filename)
        #delete two + .sig
        filename = (two + ".sig")
        os.remove(filename)
        #delete two + .zip
        filename = (two + ".zip")
        os.remove(filename)

        two = filenamepkotpkey
        ### copy two from message to current directory
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("MESSAGE")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ( two )
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = (two)
        destination = (os.path.join(currentDirectory, filenamepk))
        newpath = shutil.copy(source, destination)
        print (newpath)
        os.remove(source)
        # delete keys
        os.remove("pk.txt")
        os.remove("sk.txt")
        # copy pk.txt from frodo
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("keysfrodo")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ("pk" + one + ".txt")
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = ("pk" + ".txt")
        destination = (os.path.join(currentDirectory, filenamepk))
        newpath = shutil.copy(source, destination)
        # copy sk.txt from frodo
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("keysfrodo")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ("pk" + one + ".txt")
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = ("sk" + ".txt")
        destination = (os.path.join(currentDirectory, filenamepk))
        newpath = shutil.copy(source, destination)
        #pause = (input("hit enter to continue: "))
        temp = os.system('python enc1.py')
        symfile = ("gpg --yes --batch --passphrase=" + str(temp) + " --symmetric --cipher-algo CAMELLIA256 " + two )
        print (symfile)
        os.system(symfile)
        #pause = (input("hit enter to continue: "))
        # delete keys
        os.remove("pk.txt")
        os.remove("sk.txt")
        # copy pk.txt from falcon
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("keysfalcon")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ("pk" + three + ".txt")
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = ("pk" + ".txt")
        destination = (os.path.join(currentDirectory, filenamepk))
        shutil.copy(source, destination)
        # copy sk.txt from falcon
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("keysfalcon")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ("sk" + three + ".txt")
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = ("sk" + ".txt")
        destination = (os.path.join(currentDirectory, filenamepk))
        shutil.copy(source, destination)
        # python SignFile with file 
        signfile = ("python SignFile.py " + two + " " + two + ".sig" )
        os.system( signfile )
        #pause = (input("hit enter to continue: "))
        # copy ct to msg directory 
        #currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = ("ct" + ".txt")
        #source = (os.path.join(currentDirectory, filenamepk))
        #currentDirectory = os.path.abspath(os.getcwd())
        #subdir = ("MESSAGE")
        #currentDirectory = (os.path.join(currentDirectory, subdir))
        #filenamepk = ("ct" + ".txt")
        #destination = (os.path.join(currentDirectory, filenamepk)) 
        #shutil.copy(source, destination)
        # copy gpg to msg directory
        #currentDirectory = os.path.abspath(os.getcwd())
        filenamepk1 = (two + ".gpg")
        #source = (os.path.join(currentDirectory, filenamepk1))
        #currentDirectory = os.path.abspath(os.getcwd())
        #subdir = ("MESSAGE")
        #currentDirectory = (os.path.join(currentDirectory, subdir))
        #filenamepk1 = (two + ".gpg")
        #destination = (os.path.join(currentDirectory, filenamepk1)) 
        #shutil.copy(source, destination)        
        # copy sig to msg directory
        #currentDirectory = os.path.abspath(os.getcwd())
        filenamepk2 = (two + ".sig")
        #source = (os.path.join(currentDirectory, filenamepk2))
        #currentDirectory = os.path.abspath(os.getcwd())
        #subdir = ("MESSAGE")
        #currentDirectory = (os.path.join(currentDirectory, subdir))
        #filenamepk2 = (two + ".sig")
        #destination = (os.path.join(currentDirectory, filenamepk2)) 
        #shutil.copy(source, destination) 
        #create zipfile
        # create a ZipFile object
        zipObj = ZipFile(two + ".zip", "w")
        # Add multiple files to the zip
        zipObj.write("ct" + ".txt")
        zipObj.write(two + ".gpg")
        zipObj.write(two + ".sig")
        # close the Zip File
        zipObj.close()  
        # copy zipObj to msg directory 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = (two + ".zip")
        source = (os.path.join(currentDirectory, filenamepk))
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("MESSAGE")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = (two + ".zip")
        destination = (os.path.join(currentDirectory, filenamepk)) 
        shutil.copy(source, destination)     
        #delete ct
        os.remove("ct.txt")
        #delete two 
        filename = (two)
        os.remove(filename)
        #delete two + .gpg
        filename = (two + ".gpg")
        os.remove(filename)
        #delete two + .sig
        filename = (two + ".sig")
        os.remove(filename)
        #delete two + .zip
        filename = (two + ".zip")
        os.remove(filename)

        #pause = (input("hit enter to continue: "))
        #clear screen
        print("\033[H\033[J")


def OTPDecrypt():
        one = e.get()
        two = e1.get()
        three = e2.get()
        #clear screen
        print("\033[H\033[J")

        print("Menu 6 has been selected")
        print("*** OTP Decrypting Message")

        twootp = two
        # copy two + .zip from message to current directory
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("MESSAGE")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ( two + ".zip" )
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = (two + ".zip")
        destination = (os.path.join(currentDirectory, filenamepk))
        newpath = shutil.copy(source, destination)
        print (newpath)
        os.remove(source)
        # Create a ZipFile Object and load sample.zip in it
        with ZipFile(two + ".zip", 'r') as zipObj:
        # Extract all the contents of zip file in different directory
           zipObj.extractall("MESSAGE")
        print("*** Decrypting Message")
        #delete two + .zip
        filename = (two + ".zip")
        os.remove(filename)
        # copy ct.txt from message to current directory
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("MESSAGE")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ( "ct.txt" )
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = ("ct.txt")
        destination = (os.path.join(currentDirectory, filenamepk))
        newpath = shutil.copy(source, destination)
        print (newpath)
        os.remove(source)
        # copy two.gpg from message to current directory
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("MESSAGE")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ( two + ".gpg")
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = (two + ".gpg")
        destination = (os.path.join(currentDirectory, filenamepk))
        newpath = shutil.copy(source, destination)
        print (newpath)
        os.remove(source)
        # copy two.sig from message to current directory
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("MESSAGE")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ( two + ".sig" )
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = (two + ".sig")
        destination = (os.path.join(currentDirectory, filenamepk))
        newpath = shutil.copy(source, destination)
        print (newpath)
        os.remove(source)
        # delete keys
        os.remove("pk.txt")
        os.remove("sk.txt")
        # copy pk.txt from frodo
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("keysfrodo")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ("pk" + one + ".txt")
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = ("pk" + ".txt")
        destination = (os.path.join(currentDirectory, filenamepk))
        shutil.copy(source, destination)
        # copy sk.txt from frodo
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("keysfrodo")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ("sk" + one + ".txt")
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = ("sk" + ".txt")
        destination = (os.path.join(currentDirectory, filenamepk))
        shutil.copy(source, destination)
        #pause = (input("hit enter to continue: "))
        #os.system('python dec.py')
        #symfile = ("gpg -o " + two + " -d " + two + ".gpg")
        os.system('python Dec1.py')
        temp = os.system('python Dec1.py')
        temp= str(temp)
        symfile = ("gpg  --yes --batch --passphrase=" + temp + " -o " + two + " -d " + two + ".gpg")
        print(symfile)
        #pause = (input("hit enter to continue: "))
        os.system(symfile)
        #pause = (input("hit enter to continue: "))
        # delete keys
        os.remove("pk.txt")
        os.remove("sk.txt")
        # copy pk.txt from falcon
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("keysfalcon")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ("pk" + three + ".txt")
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = ("pk" + ".txt")
        destination = (os.path.join(currentDirectory, filenamepk))
        shutil.copy(source, destination)
        # copy sk.txt from falcon
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("keysfalcon")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ("pk" + three + ".txt")
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = ("sk" + ".txt")
        destination = (os.path.join(currentDirectory, filenamepk))
        shutil.copy(source, destination)
        # python VerifyFile with file 
        signfile = ("python VerifyFile.py " + two + " " + two + ".sig" )
        os.system( signfile )
        #pause = (input("hit enter to continue: "))
        # copy ct to msg directory 
        #currentDirectory = os.path.abspath(os.getcwd())
        #filenamepk = ("ct" + ".txt")
        #source = (os.path.join(currentDirectory, filenamepk))
        #currentDirectory = os.path.abspath(os.getcwd())
        #subdir = ("MESSAGE")
        #currentDirectory = (os.path.join(currentDirectory, subdir))
        #filenamepk = ("ct" + ".txt")
        #destination = (os.path.join(currentDirectory, filenamepk)) 
        #shutil.copy(source, destination)
        # copy two to msg directory
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = (two)
        source = (os.path.join(currentDirectory, filenamepk))
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("MESSAGE")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = (two)
        destination = (os.path.join(currentDirectory, filenamepk)) 
        shutil.copy(source, destination)        
        # copy gpg to msg directory
        #currentDirectory = os.path.abspath(os.getcwd())
        #filenamepk = (two + ".gpg")
        #source = (os.path.join(currentDirectory, filenamepk))
        #currentDirectory = os.path.abspath(os.getcwd())
        #subdir = ("MESSAGE")
        #currentDirectory = (os.path.join(currentDirectory, subdir))
        #filenamepk = (two + ".gpg")
        #destination = (os.path.join(currentDirectory, filenamepk)) 
        #shutil.copy(source, destination)        
        # copy sig to msg directory
        #currentDirectory = os.path.abspath(os.getcwd())
        #filenamepk = (two + ".sig")
        #source = (os.path.join(currentDirectory, filenamepk))
        #currentDirectory = os.path.abspath(os.getcwd())
        #subdir = ("MESSAGE")
        #currentDirectory = (os.path.join(currentDirectory, subdir))
        #filenamepk = (two + ".sig")
        #destination = (os.path.join(currentDirectory, filenamepk)) 
        #shutil.copy(source, destination)  
        #delete ct
        os.remove("ct.txt")
        #delete two 
        filename = (two)
        os.remove(filename)
        #delete two + .gpg
        filename = (two + ".gpg")
        os.remove(filename)
        #delete two + .sig
        filename = (two + ".sig")
        os.remove(filename)

        two = "keyotp.txt"
        # copy two + .zip from message to current directory
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("MESSAGE")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ( two + ".zip" )
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = (two + ".zip")
        destination = (os.path.join(currentDirectory, filenamepk))
        newpath = shutil.copy(source, destination)
        print (newpath)
        os.remove(source)
        # Create a ZipFile Object and load sample.zip in it
        with ZipFile(two + ".zip", 'r') as zipObj:
        # Extract all the contents of zip file in different directory
           zipObj.extractall("MESSAGE")
        print("*** Decrypting Message")
        #delete two + .zip
        filename = (two + ".zip")
        os.remove(filename)
        # copy ct.txt from message to current directory
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("MESSAGE")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ( "ct.txt" )
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = ("ct.txt")
        destination = (os.path.join(currentDirectory, filenamepk))
        newpath = shutil.copy(source, destination)
        print (newpath)
        os.remove(source)
        # copy two.gpg from message to current directory
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("MESSAGE")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ( two + ".gpg")
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = (two + ".gpg")
        destination = (os.path.join(currentDirectory, filenamepk))
        newpath = shutil.copy(source, destination)
        print (newpath)
        os.remove(source)
        # copy two.sig from message to current directory
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("MESSAGE")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ( two + ".sig" )
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = (two + ".sig")
        destination = (os.path.join(currentDirectory, filenamepk))
        newpath = shutil.copy(source, destination)
        print (newpath)
        os.remove(source)
        # delete keys
        os.remove("pk.txt")
        os.remove("sk.txt")
        # copy pk.txt from frodo
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("keysfrodo")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ("pk" + one + ".txt")
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = ("pk" + ".txt")
        destination = (os.path.join(currentDirectory, filenamepk))
        shutil.copy(source, destination)
        # copy sk.txt from frodo
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("keysfrodo")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ("sk" + one + ".txt")
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = ("sk" + ".txt")
        destination = (os.path.join(currentDirectory, filenamepk))
        shutil.copy(source, destination)
        #pause = (input("hit enter to continue: "))
        #os.system('python dec.py')
        #symfile = ("gpg -o " + two + " -d " + two + ".gpg")
        os.system('python Dec1.py')
        temp = os.system('python Dec1.py')
        temp= str(temp)
        symfile = ("gpg  --yes --batch --passphrase=" + temp + " -o " + two + " -d " + two + ".gpg")
        print(symfile)
        #pause = (input("hit enter to continue: "))
        os.system(symfile)
        #pause = (input("hit enter to continue: "))
        # delete keys
        os.remove("pk.txt")
        os.remove("sk.txt")
        # copy pk.txt from falcon
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("keysfalcon")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ("pk" + three + ".txt")
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = ("pk" + ".txt")
        destination = (os.path.join(currentDirectory, filenamepk))
        shutil.copy(source, destination)
        # copy sk.txt from falcon
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("keysfalcon")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ("pk" + three + ".txt")
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = ("sk" + ".txt")
        destination = (os.path.join(currentDirectory, filenamepk))
        shutil.copy(source, destination)
        # python VerifyFile with file 
        signfile = ("python VerifyFile.py " + two + " " + two + ".sig" )
        os.system( signfile )
        #pause = (input("hit enter to continue: "))
        # copy ct to msg directory 
        #currentDirectory = os.path.abspath(os.getcwd())
        #filenamepk = ("ct" + ".txt")
        #source = (os.path.join(currentDirectory, filenamepk))
        #currentDirectory = os.path.abspath(os.getcwd())
        #subdir = ("MESSAGE")
        #currentDirectory = (os.path.join(currentDirectory, subdir))
        #filenamepk = ("ct" + ".txt")
        #destination = (os.path.join(currentDirectory, filenamepk)) 
        #shutil.copy(source, destination)
        # copy two to msg directory
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = (two)
        source = (os.path.join(currentDirectory, filenamepk))
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("MESSAGE")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = (two)
        destination = (os.path.join(currentDirectory, filenamepk)) 
        shutil.copy(source, destination)        
        # copy gpg to msg directory
        #currentDirectory = os.path.abspath(os.getcwd())
        #filenamepk = (two + ".gpg")
        #source = (os.path.join(currentDirectory, filenamepk))
        #currentDirectory = os.path.abspath(os.getcwd())
        #subdir = ("MESSAGE")
        #currentDirectory = (os.path.join(currentDirectory, subdir))
        #filenamepk = (two + ".gpg")
        #destination = (os.path.join(currentDirectory, filenamepk)) 
        #shutil.copy(source, destination)        
        # copy sig to msg directory
        #currentDirectory = os.path.abspath(os.getcwd())
        #filenamepk = (two + ".sig")
        #source = (os.path.join(currentDirectory, filenamepk))
        #currentDirectory = os.path.abspath(os.getcwd())
        #subdir = ("MESSAGE")
        #currentDirectory = (os.path.join(currentDirectory, subdir))
        #filenamepk = (two + ".sig")
        #destination = (os.path.join(currentDirectory, filenamepk)) 
        #shutil.copy(source, destination)  
        #delete ct
        os.remove("ct.txt")
        #delete two 
        filename = (two)
        os.remove(filename)
        #delete two + .gpg
        filename = (two + ".gpg")
        os.remove(filename)
        #delete two + .sig
        filename = (two + ".sig")
        os.remove(filename)

        two = twootp#[:-4]
        # copy one from message to current directory
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("MESSAGE")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ( "keyotp.txt" )
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = ("keyotp.txt" )
        destination = (os.path.join(currentDirectory, filenamepk))
        newpath = shutil.copy(source, destination)
        print (newpath)
        os.remove(source)
        # copy two from message to current directory
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("MESSAGE")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = ( two )
        source = (os.path.join(currentDirectory, filenamepk)) 
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = (two + ".otp")
        destination = (os.path.join(currentDirectory, filenamepk))
        newpath = shutil.copy(source, destination)
        print (newpath)
        os.remove(source)
        #pause = (input("hit enter to continue: "))
        symfile = ("python xordec.py " + two + ".otp" + " keyotp.txt " + twootp[:-4]  )
        print (symfile)
        os.system(symfile)
        #pause = (input("hit enter to continue: "))
        # copy two to message directory
        #currentDirectory = os.path.abspath(os.getcwd())
        #filenamepk = (two + ".otp")
        #source = (os.path.join(currentDirectory, filenamepk))
        #currentDirectory = os.path.abspath(os.getcwd())
        #subdir = ("MESSAGE")
        #currentDirectory = (os.path.join(currentDirectory, subdir))
        #filenamepk = (two + ".otp")
        #destination = (os.path.join(currentDirectory, filenamepk)) 
        #shutil.copy(source, destination)
        # copy two from to message directory
        currentDirectory = os.path.abspath(os.getcwd())
        filenamepk = (twootp[:-4])
        source = (os.path.join(currentDirectory, filenamepk))
        currentDirectory = os.path.abspath(os.getcwd())
        subdir = ("MESSAGE")
        currentDirectory = (os.path.join(currentDirectory, subdir))
        filenamepk = (twootp[:-4])
        destination = (os.path.join(currentDirectory, filenamepk)) 
        shutil.copy(source, destination)
        # copy keyotp.txt to msg directory
        #currentDirectory = os.path.abspath(os.getcwd())
        #filenamepk = ("keyotp.txt")
        #source = (os.path.join(currentDirectory, filenamepk))
        #currentDirectory = os.path.abspath(os.getcwd())
        #subdir = ("MESSAGE")
        #currentDirectory = (os.path.join(currentDirectory, subdir))
        #filenamepk = ("keyotp.txt")
        #destination = (os.path.join(currentDirectory, filenamepk)) 
        #shutil.copy(source, destination) 
        #delete twootp[:-4]
        os.remove(twootp[:-4])           
        #delete two
        #os.remove(two)         
        #delete .otp
        os.remove(two + ".otp")
        #delete keyotp.txt 
        filename = ("keyotp.txt")
        os.remove(filename)
        #clear screen
        #print("\033[H\033[J")

myButton = tk.Button(root, text = "EncryptAES256", command=EncryptAES256, fg="blue", bg="orange",  borderwidth=13)
#myButton.pack()
myButton.grid(row=3,column=0)

myButton1 = tk.Button(root, text = "EncryptCAMELLIA256", command=EncryptCAMELLIA256, fg="blue", bg="orange",  borderwidth=13)
#myButton1.pack()
myButton1.grid(row=3,column=1)

myButton2 = tk.Button(root, text = "Decrypt", command=Decrypt, fg="blue", bg="orange",  borderwidth=13)
#myButton2.pack()
myButton2.grid(row=3,column=2)

myButton3 = tk.Button(root, text = "KeyGenFrodo", command=KeyGenFrodo, fg="blue", bg="orange",  borderwidth=13)
#myButton3.pack()
myButton3.grid(row=4,column=0)

myButton4 = tk.Button(root, text = "KeyGenFalcon", command=KeyGenFalcon, fg="blue", bg="orange",  borderwidth=13)
#myButton4.pack()
myButton4.grid(row=4,column=1)

myButton5 = tk.Button(root, text = "OTPEncryptAES256", command=OTPEncryptAES256, fg="blue", bg="orange",  borderwidth=13)
#myButton2.pack()
myButton5.grid(row=5,column=0)

myButton6 = tk.Button(root, text = "OTPEncryptCAMELLIA256", command=OTPEncryptCAMELLIA256, fg="blue", bg="orange",  borderwidth=13)
#myButton3.pack()
myButton6.grid(row=5,column=1)

myButton7 = tk.Button(root, text = "OTPDecrypt", command=OTPDecrypt, fg="blue", bg="orange",  borderwidth=13)
#myButton4.pack()
myButton7.grid(row=5,column=2)


root.mainloop()
 
